
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.pookie.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.pookie.block.VoidlanternBlock;
import net.mcreator.pookie.block.TopazOreBlock;
import net.mcreator.pookie.block.TopazBlockBlock;
import net.mcreator.pookie.block.SunstoneOreBlock;
import net.mcreator.pookie.block.SunstoneBlockBlock;
import net.mcreator.pookie.block.SteelventstairsBlock;
import net.mcreator.pookie.block.SteelventslabBlock;
import net.mcreator.pookie.block.SteelventblockBlock;
import net.mcreator.pookie.block.SteeltrussblockBlock;
import net.mcreator.pookie.block.SteelsheetstairsBlock;
import net.mcreator.pookie.block.SteelsheetslabBlock;
import net.mcreator.pookie.block.SteelsheetblockBlock;
import net.mcreator.pookie.block.SteelplatestairsBlock;
import net.mcreator.pookie.block.SteelplateslabBlock;
import net.mcreator.pookie.block.SteelplateblockBlock;
import net.mcreator.pookie.block.SteelboardstairsBlock;
import net.mcreator.pookie.block.SteelboardslabBlock;
import net.mcreator.pookie.block.SteelboardblockBlock;
import net.mcreator.pookie.block.StarstoneBlock;
import net.mcreator.pookie.block.StargrassBlock;
import net.mcreator.pookie.block.StardirtBlock;
import net.mcreator.pookie.block.SentianceBlock;
import net.mcreator.pookie.block.SaphireOreBlock;
import net.mcreator.pookie.block.SaphireBlockBlock;
import net.mcreator.pookie.block.RutilesOreBlock;
import net.mcreator.pookie.block.RutilesBlockBlock;
import net.mcreator.pookie.block.RubyOreBlock;
import net.mcreator.pookie.block.RubyBlockBlock;
import net.mcreator.pookie.block.RosequartzOreBlock;
import net.mcreator.pookie.block.RosequartzBlockBlock;
import net.mcreator.pookie.block.RhyoliteOreBlock;
import net.mcreator.pookie.block.RhyoliteBlockBlock;
import net.mcreator.pookie.block.PurifiedastraliumBlock;
import net.mcreator.pookie.block.PressurizerBlock;
import net.mcreator.pookie.block.PressurizedmercuryBlock;
import net.mcreator.pookie.block.PeridotOreBlock;
import net.mcreator.pookie.block.PeridotBlockBlock;
import net.mcreator.pookie.block.PedroliumOreBlock;
import net.mcreator.pookie.block.PedroliumBlockBlock;
import net.mcreator.pookie.block.OpalOreBlock;
import net.mcreator.pookie.block.OpalBlockBlock;
import net.mcreator.pookie.block.OnionblockBlock;
import net.mcreator.pookie.block.NullzonePortalBlock;
import net.mcreator.pookie.block.NebulaOreBlock;
import net.mcreator.pookie.block.NebulaBlockBlock;
import net.mcreator.pookie.block.MagmiteOreBlock;
import net.mcreator.pookie.block.MagmiteBlockBlock;
import net.mcreator.pookie.block.GiantstrawberryBlock;
import net.mcreator.pookie.block.GhostcheeseblockBlock;
import net.mcreator.pookie.block.FloweringpoisonBlock;
import net.mcreator.pookie.block.ExplosivedrillBlock;
import net.mcreator.pookie.block.DimesnioncblockBlock;
import net.mcreator.pookie.block.DimensionPortalBlock;
import net.mcreator.pookie.block.CoolantOreBlock;
import net.mcreator.pookie.block.CoolantBlockBlock;
import net.mcreator.pookie.block.CheeseblockBlock;
import net.mcreator.pookie.block.BlackironOreBlock;
import net.mcreator.pookie.block.BlackironBlockBlock;
import net.mcreator.pookie.block.AstralPortalBlock;
import net.mcreator.pookie.block.AquamarineOreBlock;
import net.mcreator.pookie.block.AquamarineBlockBlock;
import net.mcreator.pookie.block.AncienteggBlock;
import net.mcreator.pookie.block.AlexandriteOreBlock;
import net.mcreator.pookie.block.AlexandriteBlockBlock;
import net.mcreator.pookie.block.AUIJKGHNJUBlock;
import net.mcreator.pookie.PookieMod;

public class PookieModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, PookieMod.MODID);
	public static final RegistryObject<Block> DIMESNIONCBLOCK = REGISTRY.register("dimesnioncblock", () -> new DimesnioncblockBlock());
	public static final RegistryObject<Block> DIMENSION_PORTAL = REGISTRY.register("dimension_portal", () -> new DimensionPortalBlock());
	public static final RegistryObject<Block> ANCIENTEGG = REGISTRY.register("ancientegg", () -> new AncienteggBlock());
	public static final RegistryObject<Block> GIANTSTRAWBERRY = REGISTRY.register("giantstrawberry", () -> new GiantstrawberryBlock());
	public static final RegistryObject<Block> ONIONBLOCK = REGISTRY.register("onionblock", () -> new OnionblockBlock());
	public static final RegistryObject<Block> SUNSTONE_ORE = REGISTRY.register("sunstone_ore", () -> new SunstoneOreBlock());
	public static final RegistryObject<Block> SUNSTONE_BLOCK = REGISTRY.register("sunstone_block", () -> new SunstoneBlockBlock());
	public static final RegistryObject<Block> NEBULA_ORE = REGISTRY.register("nebula_ore", () -> new NebulaOreBlock());
	public static final RegistryObject<Block> NEBULA_BLOCK = REGISTRY.register("nebula_block", () -> new NebulaBlockBlock());
	public static final RegistryObject<Block> TOPAZ_ORE = REGISTRY.register("topaz_ore", () -> new TopazOreBlock());
	public static final RegistryObject<Block> TOPAZ_BLOCK = REGISTRY.register("topaz_block", () -> new TopazBlockBlock());
	public static final RegistryObject<Block> RUBY_ORE = REGISTRY.register("ruby_ore", () -> new RubyOreBlock());
	public static final RegistryObject<Block> RUBY_BLOCK = REGISTRY.register("ruby_block", () -> new RubyBlockBlock());
	public static final RegistryObject<Block> SAPHIRE_ORE = REGISTRY.register("saphire_ore", () -> new SaphireOreBlock());
	public static final RegistryObject<Block> SAPHIRE_BLOCK = REGISTRY.register("saphire_block", () -> new SaphireBlockBlock());
	public static final RegistryObject<Block> ROSEQUARTZ_ORE = REGISTRY.register("rosequartz_ore", () -> new RosequartzOreBlock());
	public static final RegistryObject<Block> ROSEQUARTZ_BLOCK = REGISTRY.register("rosequartz_block", () -> new RosequartzBlockBlock());
	public static final RegistryObject<Block> PURIFIEDASTRALIUM = REGISTRY.register("purifiedastralium", () -> new PurifiedastraliumBlock());
	public static final RegistryObject<Block> STARSTONE = REGISTRY.register("starstone", () -> new StarstoneBlock());
	public static final RegistryObject<Block> STARDIRT = REGISTRY.register("stardirt", () -> new StardirtBlock());
	public static final RegistryObject<Block> STARGRASS = REGISTRY.register("stargrass", () -> new StargrassBlock());
	public static final RegistryObject<Block> ASTRAL_PORTAL = REGISTRY.register("astral_portal", () -> new AstralPortalBlock());
	public static final RegistryObject<Block> CHEESEBLOCK = REGISTRY.register("cheeseblock", () -> new CheeseblockBlock());
	public static final RegistryObject<Block> GHOSTCHEESEBLOCK = REGISTRY.register("ghostcheeseblock", () -> new GhostcheeseblockBlock());
	public static final RegistryObject<Block> PEDROLIUM_ORE = REGISTRY.register("pedrolium_ore", () -> new PedroliumOreBlock());
	public static final RegistryObject<Block> PEDROLIUM_BLOCK = REGISTRY.register("pedrolium_block", () -> new PedroliumBlockBlock());
	public static final RegistryObject<Block> STEELPLATEBLOCK = REGISTRY.register("steelplateblock", () -> new SteelplateblockBlock());
	public static final RegistryObject<Block> FLOWERINGPOISON = REGISTRY.register("floweringpoison", () -> new FloweringpoisonBlock());
	public static final RegistryObject<Block> PRESSURIZEDMERCURY = REGISTRY.register("pressurizedmercury", () -> new PressurizedmercuryBlock());
	public static final RegistryObject<Block> VOIDLANTERN = REGISTRY.register("voidlantern", () -> new VoidlanternBlock());
	public static final RegistryObject<Block> SENTIANCE = REGISTRY.register("sentiance", () -> new SentianceBlock());
	public static final RegistryObject<Block> NULLZONE_PORTAL = REGISTRY.register("nullzone_portal", () -> new NullzonePortalBlock());
	public static final RegistryObject<Block> PERIDOT_ORE = REGISTRY.register("peridot_ore", () -> new PeridotOreBlock());
	public static final RegistryObject<Block> PERIDOT_BLOCK = REGISTRY.register("peridot_block", () -> new PeridotBlockBlock());
	public static final RegistryObject<Block> OPAL_ORE = REGISTRY.register("opal_ore", () -> new OpalOreBlock());
	public static final RegistryObject<Block> OPAL_BLOCK = REGISTRY.register("opal_block", () -> new OpalBlockBlock());
	public static final RegistryObject<Block> ALEXANDRITE_ORE = REGISTRY.register("alexandrite_ore", () -> new AlexandriteOreBlock());
	public static final RegistryObject<Block> ALEXANDRITE_BLOCK = REGISTRY.register("alexandrite_block", () -> new AlexandriteBlockBlock());
	public static final RegistryObject<Block> MAGMITE_ORE = REGISTRY.register("magmite_ore", () -> new MagmiteOreBlock());
	public static final RegistryObject<Block> MAGMITE_BLOCK = REGISTRY.register("magmite_block", () -> new MagmiteBlockBlock());
	public static final RegistryObject<Block> COOLANT_ORE = REGISTRY.register("coolant_ore", () -> new CoolantOreBlock());
	public static final RegistryObject<Block> COOLANT_BLOCK = REGISTRY.register("coolant_block", () -> new CoolantBlockBlock());
	public static final RegistryObject<Block> RHYOLITE_ORE = REGISTRY.register("rhyolite_ore", () -> new RhyoliteOreBlock());
	public static final RegistryObject<Block> RHYOLITE_BLOCK = REGISTRY.register("rhyolite_block", () -> new RhyoliteBlockBlock());
	public static final RegistryObject<Block> RUTILES_ORE = REGISTRY.register("rutiles_ore", () -> new RutilesOreBlock());
	public static final RegistryObject<Block> RUTILES_BLOCK = REGISTRY.register("rutiles_block", () -> new RutilesBlockBlock());
	public static final RegistryObject<Block> AQUAMARINE_ORE = REGISTRY.register("aquamarine_ore", () -> new AquamarineOreBlock());
	public static final RegistryObject<Block> AQUAMARINE_BLOCK = REGISTRY.register("aquamarine_block", () -> new AquamarineBlockBlock());
	public static final RegistryObject<Block> STEELPLATESTAIRS = REGISTRY.register("steelplatestairs", () -> new SteelplatestairsBlock());
	public static final RegistryObject<Block> STEELVENTSTAIRS = REGISTRY.register("steelventstairs", () -> new SteelventstairsBlock());
	public static final RegistryObject<Block> STEELVENTBLOCK = REGISTRY.register("steelventblock", () -> new SteelventblockBlock());
	public static final RegistryObject<Block> STEELSHEETBLOCK = REGISTRY.register("steelsheetblock", () -> new SteelsheetblockBlock());
	public static final RegistryObject<Block> STEELSHEETSTAIRS = REGISTRY.register("steelsheetstairs", () -> new SteelsheetstairsBlock());
	public static final RegistryObject<Block> STEELBOARDBLOCK = REGISTRY.register("steelboardblock", () -> new SteelboardblockBlock());
	public static final RegistryObject<Block> STEELBOARDSTAIRS = REGISTRY.register("steelboardstairs", () -> new SteelboardstairsBlock());
	public static final RegistryObject<Block> STEELBOARDSLAB = REGISTRY.register("steelboardslab", () -> new SteelboardslabBlock());
	public static final RegistryObject<Block> STEELPLATESLAB = REGISTRY.register("steelplateslab", () -> new SteelplateslabBlock());
	public static final RegistryObject<Block> STEELSHEETSLAB = REGISTRY.register("steelsheetslab", () -> new SteelsheetslabBlock());
	public static final RegistryObject<Block> STEELVENTSLAB = REGISTRY.register("steelventslab", () -> new SteelventslabBlock());
	public static final RegistryObject<Block> STEELTRUSSBLOCK = REGISTRY.register("steeltrussblock", () -> new SteeltrussblockBlock());
	public static final RegistryObject<Block> EXPLOSIVEDRILL = REGISTRY.register("explosivedrill", () -> new ExplosivedrillBlock());
	public static final RegistryObject<Block> AUIJKGHNJU = REGISTRY.register("auijkghnju", () -> new AUIJKGHNJUBlock());
	public static final RegistryObject<Block> PRESSURIZER = REGISTRY.register("pressurizer", () -> new PressurizerBlock());
	public static final RegistryObject<Block> BLACKIRON_ORE = REGISTRY.register("blackiron_ore", () -> new BlackironOreBlock());
	public static final RegistryObject<Block> BLACKIRON_BLOCK = REGISTRY.register("blackiron_block", () -> new BlackironBlockBlock());
}
