
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.pookie.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.pookie.item.TopazSwordItem;
import net.mcreator.pookie.item.TopazShovelItem;
import net.mcreator.pookie.item.TopazPickaxeItem;
import net.mcreator.pookie.item.TopazIngotItem;
import net.mcreator.pookie.item.TopazHoeItem;
import net.mcreator.pookie.item.TopazAxeItem;
import net.mcreator.pookie.item.TopazArmorItem;
import net.mcreator.pookie.item.SunstoneSwordItem;
import net.mcreator.pookie.item.SunstoneShovelItem;
import net.mcreator.pookie.item.SunstonePickaxeItem;
import net.mcreator.pookie.item.SunstoneHoeItem;
import net.mcreator.pookie.item.SunstoneDustItem;
import net.mcreator.pookie.item.SunstoneAxeItem;
import net.mcreator.pookie.item.SunstoneArmorItem;
import net.mcreator.pookie.item.StrawberrychunkItem;
import net.mcreator.pookie.item.SteelrodItem;
import net.mcreator.pookie.item.SteelplateItem;
import net.mcreator.pookie.item.SteelmixItem;
import net.mcreator.pookie.item.SteelingotItem;
import net.mcreator.pookie.item.SteeldiscItem;
import net.mcreator.pookie.item.SteelSwordItem;
import net.mcreator.pookie.item.SteelShovelItem;
import net.mcreator.pookie.item.SteelPickaxeItem;
import net.mcreator.pookie.item.SteelHoeItem;
import net.mcreator.pookie.item.SteelAxeItem;
import net.mcreator.pookie.item.SteelArmorItem;
import net.mcreator.pookie.item.StarItem;
import net.mcreator.pookie.item.SaphireSwordItem;
import net.mcreator.pookie.item.SaphireShovelItem;
import net.mcreator.pookie.item.SaphirePickaxeItem;
import net.mcreator.pookie.item.SaphireItem;
import net.mcreator.pookie.item.SaphireHoeItem;
import net.mcreator.pookie.item.SaphireAxeItem;
import net.mcreator.pookie.item.SaphireArmorItem;
import net.mcreator.pookie.item.RutilesSwordItem;
import net.mcreator.pookie.item.RutilesShovelItem;
import net.mcreator.pookie.item.RutilesPickaxeItem;
import net.mcreator.pookie.item.RutilesItem;
import net.mcreator.pookie.item.RutilesHoeItem;
import net.mcreator.pookie.item.RutilesAxeItem;
import net.mcreator.pookie.item.RutilesArmorItem;
import net.mcreator.pookie.item.RubySwordItem;
import net.mcreator.pookie.item.RubyShovelItem;
import net.mcreator.pookie.item.RubyPickaxeItem;
import net.mcreator.pookie.item.RubyItem;
import net.mcreator.pookie.item.RubyHoeItem;
import net.mcreator.pookie.item.RubyAxeItem;
import net.mcreator.pookie.item.RubyArmorItem;
import net.mcreator.pookie.item.RosequartzSwordItem;
import net.mcreator.pookie.item.RosequartzShovelItem;
import net.mcreator.pookie.item.RosequartzPickaxeItem;
import net.mcreator.pookie.item.RosequartzItem;
import net.mcreator.pookie.item.RosequartzHoeItem;
import net.mcreator.pookie.item.RosequartzAxeItem;
import net.mcreator.pookie.item.RosequartzArmorItem;
import net.mcreator.pookie.item.RhyoliteSwordItem;
import net.mcreator.pookie.item.RhyoliteShovelItem;
import net.mcreator.pookie.item.RhyolitePickaxeItem;
import net.mcreator.pookie.item.RhyoliteHoeItem;
import net.mcreator.pookie.item.RhyoliteDustItem;
import net.mcreator.pookie.item.RhyoliteAxeItem;
import net.mcreator.pookie.item.RhyoliteArmorItem;
import net.mcreator.pookie.item.RevexItem;
import net.mcreator.pookie.item.RedstoneSwordItem;
import net.mcreator.pookie.item.RedstoneShovelItem;
import net.mcreator.pookie.item.RedstonePickaxeItem;
import net.mcreator.pookie.item.RedstoneHoeItem;
import net.mcreator.pookie.item.RedstoneAxeItem;
import net.mcreator.pookie.item.RedstoneArmorItem;
import net.mcreator.pookie.item.QuartzSwordItem;
import net.mcreator.pookie.item.QuartzShovelItem;
import net.mcreator.pookie.item.QuartzPickaxeItem;
import net.mcreator.pookie.item.QuartzHoeItem;
import net.mcreator.pookie.item.QuartzAxeItem;
import net.mcreator.pookie.item.QuartzArmorItem;
import net.mcreator.pookie.item.PrismarineSwordItem;
import net.mcreator.pookie.item.PrismarineShovelItem;
import net.mcreator.pookie.item.PrismarinePickaxeItem;
import net.mcreator.pookie.item.PrismarineHoeItem;
import net.mcreator.pookie.item.PrismarineAxeItem;
import net.mcreator.pookie.item.PrismarineArmorItem;
import net.mcreator.pookie.item.PizzatiItem;
import net.mcreator.pookie.item.PeridotSwordItem;
import net.mcreator.pookie.item.PeridotShovelItem;
import net.mcreator.pookie.item.PeridotPickaxeItem;
import net.mcreator.pookie.item.PeridotItem;
import net.mcreator.pookie.item.PeridotHoeItem;
import net.mcreator.pookie.item.PeridotAxeItem;
import net.mcreator.pookie.item.PeridotArmorItem;
import net.mcreator.pookie.item.PedroliumSwordItem;
import net.mcreator.pookie.item.PedroliumShovelItem;
import net.mcreator.pookie.item.PedroliumPickaxeItem;
import net.mcreator.pookie.item.PedroliumItem;
import net.mcreator.pookie.item.PedroliumHoeItem;
import net.mcreator.pookie.item.PedroliumAxeItem;
import net.mcreator.pookie.item.PedroliumArmorItem;
import net.mcreator.pookie.item.PedrohgfdItem;
import net.mcreator.pookie.item.OpalSwordItem;
import net.mcreator.pookie.item.OpalShovelItem;
import net.mcreator.pookie.item.OpalPickaxeItem;
import net.mcreator.pookie.item.OpalItem;
import net.mcreator.pookie.item.OpalHoeItem;
import net.mcreator.pookie.item.OpalAxeItem;
import net.mcreator.pookie.item.OpalArmorItem;
import net.mcreator.pookie.item.OnionItem;
import net.mcreator.pookie.item.ObsidianSwordItem;
import net.mcreator.pookie.item.ObsidianShovelItem;
import net.mcreator.pookie.item.ObsidianPickaxeItem;
import net.mcreator.pookie.item.ObsidianHoeItem;
import net.mcreator.pookie.item.ObsidianAxeItem;
import net.mcreator.pookie.item.ObsidianArmorItem;
import net.mcreator.pookie.item.NullzoneItem;
import net.mcreator.pookie.item.NethercoreItem;
import net.mcreator.pookie.item.NebulaSwordItem;
import net.mcreator.pookie.item.NebulaShovelItem;
import net.mcreator.pookie.item.NebulaPickaxeItem;
import net.mcreator.pookie.item.NebulaItem;
import net.mcreator.pookie.item.NebulaHoeItem;
import net.mcreator.pookie.item.NebulaAxeItem;
import net.mcreator.pookie.item.NebulaArmorItem;
import net.mcreator.pookie.item.MaintenancemagicItem;
import net.mcreator.pookie.item.MagmiteSwordItem;
import net.mcreator.pookie.item.MagmiteShovelItem;
import net.mcreator.pookie.item.MagmitePickaxeItem;
import net.mcreator.pookie.item.MagmiteItem;
import net.mcreator.pookie.item.MagmiteHoeItem;
import net.mcreator.pookie.item.MagmiteAxeItem;
import net.mcreator.pookie.item.MagmiteArmorItem;
import net.mcreator.pookie.item.LunarItem;
import net.mcreator.pookie.item.LightningcannonItem;
import net.mcreator.pookie.item.LapisSwordItem;
import net.mcreator.pookie.item.LapisShovelItem;
import net.mcreator.pookie.item.LapisPickaxeItem;
import net.mcreator.pookie.item.LapisHoeItem;
import net.mcreator.pookie.item.LapisAxeItem;
import net.mcreator.pookie.item.LapisArmorItem;
import net.mcreator.pookie.item.HoneycombSwordItem;
import net.mcreator.pookie.item.HoneycombShovelItem;
import net.mcreator.pookie.item.HoneycombPickaxeItem;
import net.mcreator.pookie.item.HoneycombHoeItem;
import net.mcreator.pookie.item.HoneycombAxeItem;
import net.mcreator.pookie.item.HoneycombArmorItem;
import net.mcreator.pookie.item.GhostcheeseItem;
import net.mcreator.pookie.item.GalaxydemicoreItem;
import net.mcreator.pookie.item.FloweringpoisonItem;
import net.mcreator.pookie.item.FattwigItem;
import net.mcreator.pookie.item.EndichiteSwordItem;
import net.mcreator.pookie.item.EndichiteShovelItem;
import net.mcreator.pookie.item.EndichitePickaxeItem;
import net.mcreator.pookie.item.EndichiteHoeItem;
import net.mcreator.pookie.item.EndichiteAxeItem;
import net.mcreator.pookie.item.EndichiteArmorItem;
import net.mcreator.pookie.item.EndercoreItem;
import net.mcreator.pookie.item.EmereldSwordItem;
import net.mcreator.pookie.item.EmereldShovelItem;
import net.mcreator.pookie.item.EmereldPickaxeItem;
import net.mcreator.pookie.item.EmereldHoeItem;
import net.mcreator.pookie.item.EmereldAxeItem;
import net.mcreator.pookie.item.EmereldArmorItem;
import net.mcreator.pookie.item.EchoSwordItem;
import net.mcreator.pookie.item.EchoShovelItem;
import net.mcreator.pookie.item.EchoPickaxeItem;
import net.mcreator.pookie.item.EchoHoeItem;
import net.mcreator.pookie.item.EchoAxeItem;
import net.mcreator.pookie.item.EchoArmorItem;
import net.mcreator.pookie.item.EarthcoreItem;
import net.mcreator.pookie.item.DontplaythisItem;
import net.mcreator.pookie.item.DimensionItem;
import net.mcreator.pookie.item.DickonastickItem;
import net.mcreator.pookie.item.DarlingItem;
import net.mcreator.pookie.item.CopperSwordItem;
import net.mcreator.pookie.item.CopperShovelItem;
import net.mcreator.pookie.item.CopperPickaxeItem;
import net.mcreator.pookie.item.CopperHoeItem;
import net.mcreator.pookie.item.CopperAxeItem;
import net.mcreator.pookie.item.CopperArmorItem;
import net.mcreator.pookie.item.CoolantSwordItem;
import net.mcreator.pookie.item.CoolantShovelItem;
import net.mcreator.pookie.item.CoolantPickaxeItem;
import net.mcreator.pookie.item.CoolantIngotItem;
import net.mcreator.pookie.item.CoolantHoeItem;
import net.mcreator.pookie.item.CoolantAxeItem;
import net.mcreator.pookie.item.CoolantArmorItem;
import net.mcreator.pookie.item.CookiecatItem;
import net.mcreator.pookie.item.CheesemoontriggerItem;
import net.mcreator.pookie.item.CheeseItem;
import net.mcreator.pookie.item.BreadSwordItem;
import net.mcreator.pookie.item.BreadShovelItem;
import net.mcreator.pookie.item.BreadPickaxeItem;
import net.mcreator.pookie.item.BreadHoeItem;
import net.mcreator.pookie.item.BreadAxeItem;
import net.mcreator.pookie.item.BreadArmorItem;
import net.mcreator.pookie.item.BlackironSwordItem;
import net.mcreator.pookie.item.BlackironShovelItem;
import net.mcreator.pookie.item.BlackironPickaxeItem;
import net.mcreator.pookie.item.BlackironItem;
import net.mcreator.pookie.item.BlackironHoeItem;
import net.mcreator.pookie.item.BlackironAxeItem;
import net.mcreator.pookie.item.BlackironArmorItem;
import net.mcreator.pookie.item.BatteryItem;
import net.mcreator.pookie.item.BaguetteItem;
import net.mcreator.pookie.item.AstralItem;
import net.mcreator.pookie.item.AquamarineSwordItem;
import net.mcreator.pookie.item.AquamarineShovelItem;
import net.mcreator.pookie.item.AquamarinePickaxeItem;
import net.mcreator.pookie.item.AquamarineItem;
import net.mcreator.pookie.item.AquamarineHoeItem;
import net.mcreator.pookie.item.AquamarineAxeItem;
import net.mcreator.pookie.item.AquamarineArmorItem;
import net.mcreator.pookie.item.AmethystSwordItem;
import net.mcreator.pookie.item.AmethystShovelItem;
import net.mcreator.pookie.item.AmethystPickaxeItem;
import net.mcreator.pookie.item.AmethystHoeItem;
import net.mcreator.pookie.item.AmethystAxeItem;
import net.mcreator.pookie.item.AmethystArmorItem;
import net.mcreator.pookie.item.AlexandriteSwordItem;
import net.mcreator.pookie.item.AlexandriteShovelItem;
import net.mcreator.pookie.item.AlexandritePickaxeItem;
import net.mcreator.pookie.item.AlexandriteItem;
import net.mcreator.pookie.item.AlexandriteHoeItem;
import net.mcreator.pookie.item.AlexandriteAxeItem;
import net.mcreator.pookie.item.AlexandriteArmorItem;
import net.mcreator.pookie.PookieMod;

public class PookieModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, PookieMod.MODID);
	public static final RegistryObject<Item> DIMESNIONCBLOCK = block(PookieModBlocks.DIMESNIONCBLOCK);
	public static final RegistryObject<Item> DIMENSION = REGISTRY.register("dimension", () -> new DimensionItem());
	public static final RegistryObject<Item> WEURM_SPAWN_EGG = REGISTRY.register("weurm_spawn_egg", () -> new ForgeSpawnEggItem(PookieModEntities.WEURM, -3407821, -1, new Item.Properties()));
	public static final RegistryObject<Item> ALBINORAT_SPAWN_EGG = REGISTRY.register("albinorat_spawn_egg", () -> new ForgeSpawnEggItem(PookieModEntities.ALBINORAT, -1, -26113, new Item.Properties()));
	public static final RegistryObject<Item> STRAWBERRYCHUNK = REGISTRY.register("strawberrychunk", () -> new StrawberrychunkItem());
	public static final RegistryObject<Item> ANCIENTEGG = block(PookieModBlocks.ANCIENTEGG);
	public static final RegistryObject<Item> GIANTSTRAWBERRY = block(PookieModBlocks.GIANTSTRAWBERRY);
	public static final RegistryObject<Item> ONION = REGISTRY.register("onion", () -> new OnionItem());
	public static final RegistryObject<Item> ONIONBLOCK = block(PookieModBlocks.ONIONBLOCK);
	public static final RegistryObject<Item> BAGUETTE = REGISTRY.register("baguette", () -> new BaguetteItem());
	public static final RegistryObject<Item> COOKIECAT = REGISTRY.register("cookiecat", () -> new CookiecatItem());
	public static final RegistryObject<Item> SUNSTONE_DUST = REGISTRY.register("sunstone_dust", () -> new SunstoneDustItem());
	public static final RegistryObject<Item> SUNSTONE_ORE = block(PookieModBlocks.SUNSTONE_ORE);
	public static final RegistryObject<Item> SUNSTONE_BLOCK = block(PookieModBlocks.SUNSTONE_BLOCK);
	public static final RegistryObject<Item> SUNSTONE_PICKAXE = REGISTRY.register("sunstone_pickaxe", () -> new SunstonePickaxeItem());
	public static final RegistryObject<Item> SUNSTONE_AXE = REGISTRY.register("sunstone_axe", () -> new SunstoneAxeItem());
	public static final RegistryObject<Item> SUNSTONE_SWORD = REGISTRY.register("sunstone_sword", () -> new SunstoneSwordItem());
	public static final RegistryObject<Item> SUNSTONE_SHOVEL = REGISTRY.register("sunstone_shovel", () -> new SunstoneShovelItem());
	public static final RegistryObject<Item> SUNSTONE_HOE = REGISTRY.register("sunstone_hoe", () -> new SunstoneHoeItem());
	public static final RegistryObject<Item> NEBULA = REGISTRY.register("nebula", () -> new NebulaItem());
	public static final RegistryObject<Item> NEBULA_ORE = block(PookieModBlocks.NEBULA_ORE);
	public static final RegistryObject<Item> NEBULA_BLOCK = block(PookieModBlocks.NEBULA_BLOCK);
	public static final RegistryObject<Item> NEBULA_PICKAXE = REGISTRY.register("nebula_pickaxe", () -> new NebulaPickaxeItem());
	public static final RegistryObject<Item> NEBULA_AXE = REGISTRY.register("nebula_axe", () -> new NebulaAxeItem());
	public static final RegistryObject<Item> NEBULA_SWORD = REGISTRY.register("nebula_sword", () -> new NebulaSwordItem());
	public static final RegistryObject<Item> NEBULA_SHOVEL = REGISTRY.register("nebula_shovel", () -> new NebulaShovelItem());
	public static final RegistryObject<Item> NEBULA_HOE = REGISTRY.register("nebula_hoe", () -> new NebulaHoeItem());
	public static final RegistryObject<Item> NEBULA_ARMOR_HELMET = REGISTRY.register("nebula_armor_helmet", () -> new NebulaArmorItem.Helmet());
	public static final RegistryObject<Item> NEBULA_ARMOR_CHESTPLATE = REGISTRY.register("nebula_armor_chestplate", () -> new NebulaArmorItem.Chestplate());
	public static final RegistryObject<Item> NEBULA_ARMOR_LEGGINGS = REGISTRY.register("nebula_armor_leggings", () -> new NebulaArmorItem.Leggings());
	public static final RegistryObject<Item> NEBULA_ARMOR_BOOTS = REGISTRY.register("nebula_armor_boots", () -> new NebulaArmorItem.Boots());
	public static final RegistryObject<Item> SUNSTONE_ARMOR_HELMET = REGISTRY.register("sunstone_armor_helmet", () -> new SunstoneArmorItem.Helmet());
	public static final RegistryObject<Item> SUNSTONE_ARMOR_CHESTPLATE = REGISTRY.register("sunstone_armor_chestplate", () -> new SunstoneArmorItem.Chestplate());
	public static final RegistryObject<Item> SUNSTONE_ARMOR_LEGGINGS = REGISTRY.register("sunstone_armor_leggings", () -> new SunstoneArmorItem.Leggings());
	public static final RegistryObject<Item> SUNSTONE_ARMOR_BOOTS = REGISTRY.register("sunstone_armor_boots", () -> new SunstoneArmorItem.Boots());
	public static final RegistryObject<Item> ENDICHITE_PICKAXE = REGISTRY.register("endichite_pickaxe", () -> new EndichitePickaxeItem());
	public static final RegistryObject<Item> ENDICHITE_AXE = REGISTRY.register("endichite_axe", () -> new EndichiteAxeItem());
	public static final RegistryObject<Item> ENDICHITE_SWORD = REGISTRY.register("endichite_sword", () -> new EndichiteSwordItem());
	public static final RegistryObject<Item> ENDICHITE_SHOVEL = REGISTRY.register("endichite_shovel", () -> new EndichiteShovelItem());
	public static final RegistryObject<Item> ENDICHITE_HOE = REGISTRY.register("endichite_hoe", () -> new EndichiteHoeItem());
	public static final RegistryObject<Item> ENDICHITE_ARMOR_HELMET = REGISTRY.register("endichite_armor_helmet", () -> new EndichiteArmorItem.Helmet());
	public static final RegistryObject<Item> ENDICHITE_ARMOR_CHESTPLATE = REGISTRY.register("endichite_armor_chestplate", () -> new EndichiteArmorItem.Chestplate());
	public static final RegistryObject<Item> ENDICHITE_ARMOR_LEGGINGS = REGISTRY.register("endichite_armor_leggings", () -> new EndichiteArmorItem.Leggings());
	public static final RegistryObject<Item> ENDICHITE_ARMOR_BOOTS = REGISTRY.register("endichite_armor_boots", () -> new EndichiteArmorItem.Boots());
	public static final RegistryObject<Item> ENDERCORE = REGISTRY.register("endercore", () -> new EndercoreItem());
	public static final RegistryObject<Item> NETHERCORE = REGISTRY.register("nethercore", () -> new NethercoreItem());
	public static final RegistryObject<Item> EARTHCORE = REGISTRY.register("earthcore", () -> new EarthcoreItem());
	public static final RegistryObject<Item> REDSTONE_PICKAXE = REGISTRY.register("redstone_pickaxe", () -> new RedstonePickaxeItem());
	public static final RegistryObject<Item> REDSTONE_AXE = REGISTRY.register("redstone_axe", () -> new RedstoneAxeItem());
	public static final RegistryObject<Item> REDSTONE_SWORD = REGISTRY.register("redstone_sword", () -> new RedstoneSwordItem());
	public static final RegistryObject<Item> REDSTONE_SHOVEL = REGISTRY.register("redstone_shovel", () -> new RedstoneShovelItem());
	public static final RegistryObject<Item> REDSTONE_HOE = REGISTRY.register("redstone_hoe", () -> new RedstoneHoeItem());
	public static final RegistryObject<Item> REDSTONE_ARMOR_HELMET = REGISTRY.register("redstone_armor_helmet", () -> new RedstoneArmorItem.Helmet());
	public static final RegistryObject<Item> REDSTONE_ARMOR_CHESTPLATE = REGISTRY.register("redstone_armor_chestplate", () -> new RedstoneArmorItem.Chestplate());
	public static final RegistryObject<Item> REDSTONE_ARMOR_LEGGINGS = REGISTRY.register("redstone_armor_leggings", () -> new RedstoneArmorItem.Leggings());
	public static final RegistryObject<Item> REDSTONE_ARMOR_BOOTS = REGISTRY.register("redstone_armor_boots", () -> new RedstoneArmorItem.Boots());
	public static final RegistryObject<Item> LAPIS_PICKAXE = REGISTRY.register("lapis_pickaxe", () -> new LapisPickaxeItem());
	public static final RegistryObject<Item> LAPIS_AXE = REGISTRY.register("lapis_axe", () -> new LapisAxeItem());
	public static final RegistryObject<Item> LAPIS_SWORD = REGISTRY.register("lapis_sword", () -> new LapisSwordItem());
	public static final RegistryObject<Item> LAPIS_SHOVEL = REGISTRY.register("lapis_shovel", () -> new LapisShovelItem());
	public static final RegistryObject<Item> LAPIS_HOE = REGISTRY.register("lapis_hoe", () -> new LapisHoeItem());
	public static final RegistryObject<Item> LAPIS_ARMOR_HELMET = REGISTRY.register("lapis_armor_helmet", () -> new LapisArmorItem.Helmet());
	public static final RegistryObject<Item> LAPIS_ARMOR_CHESTPLATE = REGISTRY.register("lapis_armor_chestplate", () -> new LapisArmorItem.Chestplate());
	public static final RegistryObject<Item> LAPIS_ARMOR_LEGGINGS = REGISTRY.register("lapis_armor_leggings", () -> new LapisArmorItem.Leggings());
	public static final RegistryObject<Item> LAPIS_ARMOR_BOOTS = REGISTRY.register("lapis_armor_boots", () -> new LapisArmorItem.Boots());
	public static final RegistryObject<Item> EMERELD_PICKAXE = REGISTRY.register("emereld_pickaxe", () -> new EmereldPickaxeItem());
	public static final RegistryObject<Item> EMERELD_AXE = REGISTRY.register("emereld_axe", () -> new EmereldAxeItem());
	public static final RegistryObject<Item> EMERELD_SWORD = REGISTRY.register("emereld_sword", () -> new EmereldSwordItem());
	public static final RegistryObject<Item> EMERELD_SHOVEL = REGISTRY.register("emereld_shovel", () -> new EmereldShovelItem());
	public static final RegistryObject<Item> EMERELD_HOE = REGISTRY.register("emereld_hoe", () -> new EmereldHoeItem());
	public static final RegistryObject<Item> EMERELD_ARMOR_HELMET = REGISTRY.register("emereld_armor_helmet", () -> new EmereldArmorItem.Helmet());
	public static final RegistryObject<Item> EMERELD_ARMOR_CHESTPLATE = REGISTRY.register("emereld_armor_chestplate", () -> new EmereldArmorItem.Chestplate());
	public static final RegistryObject<Item> EMERELD_ARMOR_LEGGINGS = REGISTRY.register("emereld_armor_leggings", () -> new EmereldArmorItem.Leggings());
	public static final RegistryObject<Item> EMERELD_ARMOR_BOOTS = REGISTRY.register("emereld_armor_boots", () -> new EmereldArmorItem.Boots());
	public static final RegistryObject<Item> AMETHYST_ARMOR_HELMET = REGISTRY.register("amethyst_armor_helmet", () -> new AmethystArmorItem.Helmet());
	public static final RegistryObject<Item> AMETHYST_ARMOR_CHESTPLATE = REGISTRY.register("amethyst_armor_chestplate", () -> new AmethystArmorItem.Chestplate());
	public static final RegistryObject<Item> AMETHYST_ARMOR_LEGGINGS = REGISTRY.register("amethyst_armor_leggings", () -> new AmethystArmorItem.Leggings());
	public static final RegistryObject<Item> AMETHYST_ARMOR_BOOTS = REGISTRY.register("amethyst_armor_boots", () -> new AmethystArmorItem.Boots());
	public static final RegistryObject<Item> AMETHYST_PICKAXE = REGISTRY.register("amethyst_pickaxe", () -> new AmethystPickaxeItem());
	public static final RegistryObject<Item> AMETHYST_AXE = REGISTRY.register("amethyst_axe", () -> new AmethystAxeItem());
	public static final RegistryObject<Item> AMETHYST_SWORD = REGISTRY.register("amethyst_sword", () -> new AmethystSwordItem());
	public static final RegistryObject<Item> AMETHYST_SHOVEL = REGISTRY.register("amethyst_shovel", () -> new AmethystShovelItem());
	public static final RegistryObject<Item> AMETHYST_HOE = REGISTRY.register("amethyst_hoe", () -> new AmethystHoeItem());
	public static final RegistryObject<Item> COPPER_ARMOR_HELMET = REGISTRY.register("copper_armor_helmet", () -> new CopperArmorItem.Helmet());
	public static final RegistryObject<Item> COPPER_ARMOR_CHESTPLATE = REGISTRY.register("copper_armor_chestplate", () -> new CopperArmorItem.Chestplate());
	public static final RegistryObject<Item> COPPER_ARMOR_LEGGINGS = REGISTRY.register("copper_armor_leggings", () -> new CopperArmorItem.Leggings());
	public static final RegistryObject<Item> COPPER_ARMOR_BOOTS = REGISTRY.register("copper_armor_boots", () -> new CopperArmorItem.Boots());
	public static final RegistryObject<Item> COPPER_PICKAXE = REGISTRY.register("copper_pickaxe", () -> new CopperPickaxeItem());
	public static final RegistryObject<Item> COPPER_AXE = REGISTRY.register("copper_axe", () -> new CopperAxeItem());
	public static final RegistryObject<Item> COPPER_SWORD = REGISTRY.register("copper_sword", () -> new CopperSwordItem());
	public static final RegistryObject<Item> COPPER_SHOVEL = REGISTRY.register("copper_shovel", () -> new CopperShovelItem());
	public static final RegistryObject<Item> COPPER_HOE = REGISTRY.register("copper_hoe", () -> new CopperHoeItem());
	public static final RegistryObject<Item> TOPAZ_INGOT = REGISTRY.register("topaz_ingot", () -> new TopazIngotItem());
	public static final RegistryObject<Item> TOPAZ_ORE = block(PookieModBlocks.TOPAZ_ORE);
	public static final RegistryObject<Item> TOPAZ_BLOCK = block(PookieModBlocks.TOPAZ_BLOCK);
	public static final RegistryObject<Item> TOPAZ_PICKAXE = REGISTRY.register("topaz_pickaxe", () -> new TopazPickaxeItem());
	public static final RegistryObject<Item> TOPAZ_AXE = REGISTRY.register("topaz_axe", () -> new TopazAxeItem());
	public static final RegistryObject<Item> TOPAZ_SWORD = REGISTRY.register("topaz_sword", () -> new TopazSwordItem());
	public static final RegistryObject<Item> TOPAZ_SHOVEL = REGISTRY.register("topaz_shovel", () -> new TopazShovelItem());
	public static final RegistryObject<Item> TOPAZ_HOE = REGISTRY.register("topaz_hoe", () -> new TopazHoeItem());
	public static final RegistryObject<Item> TOPAZ_ARMOR_HELMET = REGISTRY.register("topaz_armor_helmet", () -> new TopazArmorItem.Helmet());
	public static final RegistryObject<Item> TOPAZ_ARMOR_CHESTPLATE = REGISTRY.register("topaz_armor_chestplate", () -> new TopazArmorItem.Chestplate());
	public static final RegistryObject<Item> TOPAZ_ARMOR_LEGGINGS = REGISTRY.register("topaz_armor_leggings", () -> new TopazArmorItem.Leggings());
	public static final RegistryObject<Item> TOPAZ_ARMOR_BOOTS = REGISTRY.register("topaz_armor_boots", () -> new TopazArmorItem.Boots());
	public static final RegistryObject<Item> RUBY = REGISTRY.register("ruby", () -> new RubyItem());
	public static final RegistryObject<Item> RUBY_ORE = block(PookieModBlocks.RUBY_ORE);
	public static final RegistryObject<Item> RUBY_BLOCK = block(PookieModBlocks.RUBY_BLOCK);
	public static final RegistryObject<Item> RUBY_PICKAXE = REGISTRY.register("ruby_pickaxe", () -> new RubyPickaxeItem());
	public static final RegistryObject<Item> RUBY_AXE = REGISTRY.register("ruby_axe", () -> new RubyAxeItem());
	public static final RegistryObject<Item> RUBY_SWORD = REGISTRY.register("ruby_sword", () -> new RubySwordItem());
	public static final RegistryObject<Item> RUBY_SHOVEL = REGISTRY.register("ruby_shovel", () -> new RubyShovelItem());
	public static final RegistryObject<Item> RUBY_HOE = REGISTRY.register("ruby_hoe", () -> new RubyHoeItem());
	public static final RegistryObject<Item> RUBY_ARMOR_HELMET = REGISTRY.register("ruby_armor_helmet", () -> new RubyArmorItem.Helmet());
	public static final RegistryObject<Item> RUBY_ARMOR_CHESTPLATE = REGISTRY.register("ruby_armor_chestplate", () -> new RubyArmorItem.Chestplate());
	public static final RegistryObject<Item> RUBY_ARMOR_LEGGINGS = REGISTRY.register("ruby_armor_leggings", () -> new RubyArmorItem.Leggings());
	public static final RegistryObject<Item> RUBY_ARMOR_BOOTS = REGISTRY.register("ruby_armor_boots", () -> new RubyArmorItem.Boots());
	public static final RegistryObject<Item> SAPHIRE = REGISTRY.register("saphire", () -> new SaphireItem());
	public static final RegistryObject<Item> SAPHIRE_ORE = block(PookieModBlocks.SAPHIRE_ORE);
	public static final RegistryObject<Item> SAPHIRE_BLOCK = block(PookieModBlocks.SAPHIRE_BLOCK);
	public static final RegistryObject<Item> SAPHIRE_PICKAXE = REGISTRY.register("saphire_pickaxe", () -> new SaphirePickaxeItem());
	public static final RegistryObject<Item> SAPHIRE_AXE = REGISTRY.register("saphire_axe", () -> new SaphireAxeItem());
	public static final RegistryObject<Item> SAPHIRE_SWORD = REGISTRY.register("saphire_sword", () -> new SaphireSwordItem());
	public static final RegistryObject<Item> SAPHIRE_SHOVEL = REGISTRY.register("saphire_shovel", () -> new SaphireShovelItem());
	public static final RegistryObject<Item> SAPHIRE_HOE = REGISTRY.register("saphire_hoe", () -> new SaphireHoeItem());
	public static final RegistryObject<Item> SAPHIRE_ARMOR_HELMET = REGISTRY.register("saphire_armor_helmet", () -> new SaphireArmorItem.Helmet());
	public static final RegistryObject<Item> SAPHIRE_ARMOR_CHESTPLATE = REGISTRY.register("saphire_armor_chestplate", () -> new SaphireArmorItem.Chestplate());
	public static final RegistryObject<Item> SAPHIRE_ARMOR_LEGGINGS = REGISTRY.register("saphire_armor_leggings", () -> new SaphireArmorItem.Leggings());
	public static final RegistryObject<Item> SAPHIRE_ARMOR_BOOTS = REGISTRY.register("saphire_armor_boots", () -> new SaphireArmorItem.Boots());
	public static final RegistryObject<Item> ROSEQUARTZ = REGISTRY.register("rosequartz", () -> new RosequartzItem());
	public static final RegistryObject<Item> ROSEQUARTZ_ORE = block(PookieModBlocks.ROSEQUARTZ_ORE);
	public static final RegistryObject<Item> ROSEQUARTZ_BLOCK = block(PookieModBlocks.ROSEQUARTZ_BLOCK);
	public static final RegistryObject<Item> ROSEQUARTZ_PICKAXE = REGISTRY.register("rosequartz_pickaxe", () -> new RosequartzPickaxeItem());
	public static final RegistryObject<Item> ROSEQUARTZ_AXE = REGISTRY.register("rosequartz_axe", () -> new RosequartzAxeItem());
	public static final RegistryObject<Item> ROSEQUARTZ_SWORD = REGISTRY.register("rosequartz_sword", () -> new RosequartzSwordItem());
	public static final RegistryObject<Item> ROSEQUARTZ_SHOVEL = REGISTRY.register("rosequartz_shovel", () -> new RosequartzShovelItem());
	public static final RegistryObject<Item> ROSEQUARTZ_HOE = REGISTRY.register("rosequartz_hoe", () -> new RosequartzHoeItem());
	public static final RegistryObject<Item> ROSEQUARTZ_ARMOR_HELMET = REGISTRY.register("rosequartz_armor_helmet", () -> new RosequartzArmorItem.Helmet());
	public static final RegistryObject<Item> ROSEQUARTZ_ARMOR_CHESTPLATE = REGISTRY.register("rosequartz_armor_chestplate", () -> new RosequartzArmorItem.Chestplate());
	public static final RegistryObject<Item> ROSEQUARTZ_ARMOR_LEGGINGS = REGISTRY.register("rosequartz_armor_leggings", () -> new RosequartzArmorItem.Leggings());
	public static final RegistryObject<Item> ROSEQUARTZ_ARMOR_BOOTS = REGISTRY.register("rosequartz_armor_boots", () -> new RosequartzArmorItem.Boots());
	public static final RegistryObject<Item> GALAXYDEMICORE = REGISTRY.register("galaxydemicore", () -> new GalaxydemicoreItem());
	public static final RegistryObject<Item> STAR = REGISTRY.register("star", () -> new StarItem());
	public static final RegistryObject<Item> CHEESEMOONTRIGGER = REGISTRY.register("cheesemoontrigger", () -> new CheesemoontriggerItem());
	public static final RegistryObject<Item> BREAD_PICKAXE = REGISTRY.register("bread_pickaxe", () -> new BreadPickaxeItem());
	public static final RegistryObject<Item> BREAD_AXE = REGISTRY.register("bread_axe", () -> new BreadAxeItem());
	public static final RegistryObject<Item> BREAD_SWORD = REGISTRY.register("bread_sword", () -> new BreadSwordItem());
	public static final RegistryObject<Item> BREAD_SHOVEL = REGISTRY.register("bread_shovel", () -> new BreadShovelItem());
	public static final RegistryObject<Item> BREAD_HOE = REGISTRY.register("bread_hoe", () -> new BreadHoeItem());
	public static final RegistryObject<Item> BREAD_ARMOR_HELMET = REGISTRY.register("bread_armor_helmet", () -> new BreadArmorItem.Helmet());
	public static final RegistryObject<Item> BREAD_ARMOR_CHESTPLATE = REGISTRY.register("bread_armor_chestplate", () -> new BreadArmorItem.Chestplate());
	public static final RegistryObject<Item> BREAD_ARMOR_LEGGINGS = REGISTRY.register("bread_armor_leggings", () -> new BreadArmorItem.Leggings());
	public static final RegistryObject<Item> BREAD_ARMOR_BOOTS = REGISTRY.register("bread_armor_boots", () -> new BreadArmorItem.Boots());
	public static final RegistryObject<Item> PURIFIEDASTRALIUM = block(PookieModBlocks.PURIFIEDASTRALIUM);
	public static final RegistryObject<Item> STARSTONE = block(PookieModBlocks.STARSTONE);
	public static final RegistryObject<Item> STARDIRT = block(PookieModBlocks.STARDIRT);
	public static final RegistryObject<Item> STARGRASS = block(PookieModBlocks.STARGRASS);
	public static final RegistryObject<Item> ASTRAL = REGISTRY.register("astral", () -> new AstralItem());
	public static final RegistryObject<Item> CHEESEBLOCK = block(PookieModBlocks.CHEESEBLOCK);
	public static final RegistryObject<Item> GHOSTCHEESEBLOCK = block(PookieModBlocks.GHOSTCHEESEBLOCK);
	public static final RegistryObject<Item> CHEESE = REGISTRY.register("cheese", () -> new CheeseItem());
	public static final RegistryObject<Item> GHOSTCHEESE = REGISTRY.register("ghostcheese", () -> new GhostcheeseItem());
	public static final RegistryObject<Item> MAINTENANCEMAGIC = REGISTRY.register("maintenancemagic", () -> new MaintenancemagicItem());
	public static final RegistryObject<Item> LIGHTNINGCANNON = REGISTRY.register("lightningcannon", () -> new LightningcannonItem());
	public static final RegistryObject<Item> PEDROHGFD = REGISTRY.register("pedrohgfd", () -> new PedrohgfdItem());
	public static final RegistryObject<Item> DONTPLAYTHIS = REGISTRY.register("dontplaythis", () -> new DontplaythisItem());
	public static final RegistryObject<Item> PIZZATI = REGISTRY.register("pizzati", () -> new PizzatiItem());
	public static final RegistryObject<Item> PEDROLIUM = REGISTRY.register("pedrolium", () -> new PedroliumItem());
	public static final RegistryObject<Item> PEDROLIUM_ORE = block(PookieModBlocks.PEDROLIUM_ORE);
	public static final RegistryObject<Item> PEDROLIUM_BLOCK = block(PookieModBlocks.PEDROLIUM_BLOCK);
	public static final RegistryObject<Item> PEDROLIUM_PICKAXE = REGISTRY.register("pedrolium_pickaxe", () -> new PedroliumPickaxeItem());
	public static final RegistryObject<Item> PEDROLIUM_AXE = REGISTRY.register("pedrolium_axe", () -> new PedroliumAxeItem());
	public static final RegistryObject<Item> PEDROLIUM_SWORD = REGISTRY.register("pedrolium_sword", () -> new PedroliumSwordItem());
	public static final RegistryObject<Item> PEDROLIUM_SHOVEL = REGISTRY.register("pedrolium_shovel", () -> new PedroliumShovelItem());
	public static final RegistryObject<Item> PEDROLIUM_HOE = REGISTRY.register("pedrolium_hoe", () -> new PedroliumHoeItem());
	public static final RegistryObject<Item> PEDROLIUM_ARMOR_HELMET = REGISTRY.register("pedrolium_armor_helmet", () -> new PedroliumArmorItem.Helmet());
	public static final RegistryObject<Item> PEDROLIUM_ARMOR_CHESTPLATE = REGISTRY.register("pedrolium_armor_chestplate", () -> new PedroliumArmorItem.Chestplate());
	public static final RegistryObject<Item> PEDROLIUM_ARMOR_LEGGINGS = REGISTRY.register("pedrolium_armor_leggings", () -> new PedroliumArmorItem.Leggings());
	public static final RegistryObject<Item> PEDROLIUM_ARMOR_BOOTS = REGISTRY.register("pedrolium_armor_boots", () -> new PedroliumArmorItem.Boots());
	public static final RegistryObject<Item> STEELMIX = REGISTRY.register("steelmix", () -> new SteelmixItem());
	public static final RegistryObject<Item> STEELINGOT = REGISTRY.register("steelingot", () -> new SteelingotItem());
	public static final RegistryObject<Item> STEEL_PICKAXE = REGISTRY.register("steel_pickaxe", () -> new SteelPickaxeItem());
	public static final RegistryObject<Item> STEEL_AXE = REGISTRY.register("steel_axe", () -> new SteelAxeItem());
	public static final RegistryObject<Item> STEEL_SWORD = REGISTRY.register("steel_sword", () -> new SteelSwordItem());
	public static final RegistryObject<Item> STEEL_SHOVEL = REGISTRY.register("steel_shovel", () -> new SteelShovelItem());
	public static final RegistryObject<Item> STEEL_HOE = REGISTRY.register("steel_hoe", () -> new SteelHoeItem());
	public static final RegistryObject<Item> STEEL_ARMOR_HELMET = REGISTRY.register("steel_armor_helmet", () -> new SteelArmorItem.Helmet());
	public static final RegistryObject<Item> STEEL_ARMOR_CHESTPLATE = REGISTRY.register("steel_armor_chestplate", () -> new SteelArmorItem.Chestplate());
	public static final RegistryObject<Item> STEEL_ARMOR_LEGGINGS = REGISTRY.register("steel_armor_leggings", () -> new SteelArmorItem.Leggings());
	public static final RegistryObject<Item> STEEL_ARMOR_BOOTS = REGISTRY.register("steel_armor_boots", () -> new SteelArmorItem.Boots());
	public static final RegistryObject<Item> STEELPLATE = REGISTRY.register("steelplate", () -> new SteelplateItem());
	public static final RegistryObject<Item> STEELDISC = REGISTRY.register("steeldisc", () -> new SteeldiscItem());
	public static final RegistryObject<Item> STEELPLATEBLOCK = block(PookieModBlocks.STEELPLATEBLOCK);
	public static final RegistryObject<Item> FATTWIG = REGISTRY.register("fattwig", () -> new FattwigItem());
	public static final RegistryObject<Item> ONIONCREEPER_SPAWN_EGG = REGISTRY.register("onioncreeper_spawn_egg", () -> new ForgeSpawnEggItem(PookieModEntities.ONIONCREEPER, -2382739, -13159, new Item.Properties()));
	public static final RegistryObject<Item> FLOWERINGPOISON_BUCKET = REGISTRY.register("floweringpoison_bucket", () -> new FloweringpoisonItem());
	public static final RegistryObject<Item> PRESSURIZEDMERCURY = block(PookieModBlocks.PRESSURIZEDMERCURY);
	public static final RegistryObject<Item> VOIDLANTERN = block(PookieModBlocks.VOIDLANTERN);
	public static final RegistryObject<Item> SENTIANCE = block(PookieModBlocks.SENTIANCE);
	public static final RegistryObject<Item> NULLZONE = REGISTRY.register("nullzone", () -> new NullzoneItem());
	public static final RegistryObject<Item> ECHO_ARMOR_HELMET = REGISTRY.register("echo_armor_helmet", () -> new EchoArmorItem.Helmet());
	public static final RegistryObject<Item> ECHO_ARMOR_CHESTPLATE = REGISTRY.register("echo_armor_chestplate", () -> new EchoArmorItem.Chestplate());
	public static final RegistryObject<Item> ECHO_ARMOR_LEGGINGS = REGISTRY.register("echo_armor_leggings", () -> new EchoArmorItem.Leggings());
	public static final RegistryObject<Item> ECHO_ARMOR_BOOTS = REGISTRY.register("echo_armor_boots", () -> new EchoArmorItem.Boots());
	public static final RegistryObject<Item> HONEYCOMB_ARMOR_HELMET = REGISTRY.register("honeycomb_armor_helmet", () -> new HoneycombArmorItem.Helmet());
	public static final RegistryObject<Item> HONEYCOMB_ARMOR_CHESTPLATE = REGISTRY.register("honeycomb_armor_chestplate", () -> new HoneycombArmorItem.Chestplate());
	public static final RegistryObject<Item> HONEYCOMB_ARMOR_LEGGINGS = REGISTRY.register("honeycomb_armor_leggings", () -> new HoneycombArmorItem.Leggings());
	public static final RegistryObject<Item> HONEYCOMB_ARMOR_BOOTS = REGISTRY.register("honeycomb_armor_boots", () -> new HoneycombArmorItem.Boots());
	public static final RegistryObject<Item> PRISMARINE_ARMOR_HELMET = REGISTRY.register("prismarine_armor_helmet", () -> new PrismarineArmorItem.Helmet());
	public static final RegistryObject<Item> PRISMARINE_ARMOR_CHESTPLATE = REGISTRY.register("prismarine_armor_chestplate", () -> new PrismarineArmorItem.Chestplate());
	public static final RegistryObject<Item> PRISMARINE_ARMOR_LEGGINGS = REGISTRY.register("prismarine_armor_leggings", () -> new PrismarineArmorItem.Leggings());
	public static final RegistryObject<Item> PRISMARINE_ARMOR_BOOTS = REGISTRY.register("prismarine_armor_boots", () -> new PrismarineArmorItem.Boots());
	public static final RegistryObject<Item> ECHO_PICKAXE = REGISTRY.register("echo_pickaxe", () -> new EchoPickaxeItem());
	public static final RegistryObject<Item> ECHO_AXE = REGISTRY.register("echo_axe", () -> new EchoAxeItem());
	public static final RegistryObject<Item> ECHO_SWORD = REGISTRY.register("echo_sword", () -> new EchoSwordItem());
	public static final RegistryObject<Item> ECHO_SHOVEL = REGISTRY.register("echo_shovel", () -> new EchoShovelItem());
	public static final RegistryObject<Item> ECHO_HOE = REGISTRY.register("echo_hoe", () -> new EchoHoeItem());
	public static final RegistryObject<Item> HONEYCOMB_PICKAXE = REGISTRY.register("honeycomb_pickaxe", () -> new HoneycombPickaxeItem());
	public static final RegistryObject<Item> HONEYCOMB_AXE = REGISTRY.register("honeycomb_axe", () -> new HoneycombAxeItem());
	public static final RegistryObject<Item> HONEYCOMB_SWORD = REGISTRY.register("honeycomb_sword", () -> new HoneycombSwordItem());
	public static final RegistryObject<Item> HONEYCOMB_SHOVEL = REGISTRY.register("honeycomb_shovel", () -> new HoneycombShovelItem());
	public static final RegistryObject<Item> HONEYCOMB_HOE = REGISTRY.register("honeycomb_hoe", () -> new HoneycombHoeItem());
	public static final RegistryObject<Item> PRISMARINE_PICKAXE = REGISTRY.register("prismarine_pickaxe", () -> new PrismarinePickaxeItem());
	public static final RegistryObject<Item> PRISMARINE_AXE = REGISTRY.register("prismarine_axe", () -> new PrismarineAxeItem());
	public static final RegistryObject<Item> PRISMARINE_SWORD = REGISTRY.register("prismarine_sword", () -> new PrismarineSwordItem());
	public static final RegistryObject<Item> PRISMARINE_SHOVEL = REGISTRY.register("prismarine_shovel", () -> new PrismarineShovelItem());
	public static final RegistryObject<Item> PRISMARINE_HOE = REGISTRY.register("prismarine_hoe", () -> new PrismarineHoeItem());
	public static final RegistryObject<Item> PERIDOT_ARMOR_HELMET = REGISTRY.register("peridot_armor_helmet", () -> new PeridotArmorItem.Helmet());
	public static final RegistryObject<Item> PERIDOT_ARMOR_CHESTPLATE = REGISTRY.register("peridot_armor_chestplate", () -> new PeridotArmorItem.Chestplate());
	public static final RegistryObject<Item> PERIDOT_ARMOR_LEGGINGS = REGISTRY.register("peridot_armor_leggings", () -> new PeridotArmorItem.Leggings());
	public static final RegistryObject<Item> PERIDOT_ARMOR_BOOTS = REGISTRY.register("peridot_armor_boots", () -> new PeridotArmorItem.Boots());
	public static final RegistryObject<Item> PERIDOT_ORE = block(PookieModBlocks.PERIDOT_ORE);
	public static final RegistryObject<Item> PERIDOT_BLOCK = block(PookieModBlocks.PERIDOT_BLOCK);
	public static final RegistryObject<Item> PERIDOT = REGISTRY.register("peridot", () -> new PeridotItem());
	public static final RegistryObject<Item> PERIDOT_PICKAXE = REGISTRY.register("peridot_pickaxe", () -> new PeridotPickaxeItem());
	public static final RegistryObject<Item> PERIDOT_AXE = REGISTRY.register("peridot_axe", () -> new PeridotAxeItem());
	public static final RegistryObject<Item> PERIDOT_SWORD = REGISTRY.register("peridot_sword", () -> new PeridotSwordItem());
	public static final RegistryObject<Item> PERIDOT_SHOVEL = REGISTRY.register("peridot_shovel", () -> new PeridotShovelItem());
	public static final RegistryObject<Item> PERIDOT_HOE = REGISTRY.register("peridot_hoe", () -> new PeridotHoeItem());
	public static final RegistryObject<Item> OBSIDIAN_ARMOR_HELMET = REGISTRY.register("obsidian_armor_helmet", () -> new ObsidianArmorItem.Helmet());
	public static final RegistryObject<Item> OBSIDIAN_ARMOR_CHESTPLATE = REGISTRY.register("obsidian_armor_chestplate", () -> new ObsidianArmorItem.Chestplate());
	public static final RegistryObject<Item> OBSIDIAN_ARMOR_LEGGINGS = REGISTRY.register("obsidian_armor_leggings", () -> new ObsidianArmorItem.Leggings());
	public static final RegistryObject<Item> OBSIDIAN_ARMOR_BOOTS = REGISTRY.register("obsidian_armor_boots", () -> new ObsidianArmorItem.Boots());
	public static final RegistryObject<Item> OPAL_ARMOR_HELMET = REGISTRY.register("opal_armor_helmet", () -> new OpalArmorItem.Helmet());
	public static final RegistryObject<Item> OPAL_ARMOR_CHESTPLATE = REGISTRY.register("opal_armor_chestplate", () -> new OpalArmorItem.Chestplate());
	public static final RegistryObject<Item> OPAL_ARMOR_LEGGINGS = REGISTRY.register("opal_armor_leggings", () -> new OpalArmorItem.Leggings());
	public static final RegistryObject<Item> OPAL_ARMOR_BOOTS = REGISTRY.register("opal_armor_boots", () -> new OpalArmorItem.Boots());
	public static final RegistryObject<Item> OPAL_ORE = block(PookieModBlocks.OPAL_ORE);
	public static final RegistryObject<Item> OPAL_BLOCK = block(PookieModBlocks.OPAL_BLOCK);
	public static final RegistryObject<Item> OPAL = REGISTRY.register("opal", () -> new OpalItem());
	public static final RegistryObject<Item> OBSIDIAN_PICKAXE = REGISTRY.register("obsidian_pickaxe", () -> new ObsidianPickaxeItem());
	public static final RegistryObject<Item> OBSIDIAN_AXE = REGISTRY.register("obsidian_axe", () -> new ObsidianAxeItem());
	public static final RegistryObject<Item> OBSIDIAN_SWORD = REGISTRY.register("obsidian_sword", () -> new ObsidianSwordItem());
	public static final RegistryObject<Item> OBSIDIAN_SHOVEL = REGISTRY.register("obsidian_shovel", () -> new ObsidianShovelItem());
	public static final RegistryObject<Item> OBSIDIAN_HOE = REGISTRY.register("obsidian_hoe", () -> new ObsidianHoeItem());
	public static final RegistryObject<Item> OPAL_PICKAXE = REGISTRY.register("opal_pickaxe", () -> new OpalPickaxeItem());
	public static final RegistryObject<Item> OPAL_AXE = REGISTRY.register("opal_axe", () -> new OpalAxeItem());
	public static final RegistryObject<Item> OPAL_SWORD = REGISTRY.register("opal_sword", () -> new OpalSwordItem());
	public static final RegistryObject<Item> OPAL_SHOVEL = REGISTRY.register("opal_shovel", () -> new OpalShovelItem());
	public static final RegistryObject<Item> OPAL_HOE = REGISTRY.register("opal_hoe", () -> new OpalHoeItem());
	public static final RegistryObject<Item> ALEXANDRITE_ARMOR_HELMET = REGISTRY.register("alexandrite_armor_helmet", () -> new AlexandriteArmorItem.Helmet());
	public static final RegistryObject<Item> ALEXANDRITE_ARMOR_CHESTPLATE = REGISTRY.register("alexandrite_armor_chestplate", () -> new AlexandriteArmorItem.Chestplate());
	public static final RegistryObject<Item> ALEXANDRITE_ARMOR_LEGGINGS = REGISTRY.register("alexandrite_armor_leggings", () -> new AlexandriteArmorItem.Leggings());
	public static final RegistryObject<Item> ALEXANDRITE_ARMOR_BOOTS = REGISTRY.register("alexandrite_armor_boots", () -> new AlexandriteArmorItem.Boots());
	public static final RegistryObject<Item> MAGMITE_ARMOR_HELMET = REGISTRY.register("magmite_armor_helmet", () -> new MagmiteArmorItem.Helmet());
	public static final RegistryObject<Item> MAGMITE_ARMOR_CHESTPLATE = REGISTRY.register("magmite_armor_chestplate", () -> new MagmiteArmorItem.Chestplate());
	public static final RegistryObject<Item> MAGMITE_ARMOR_LEGGINGS = REGISTRY.register("magmite_armor_leggings", () -> new MagmiteArmorItem.Leggings());
	public static final RegistryObject<Item> MAGMITE_ARMOR_BOOTS = REGISTRY.register("magmite_armor_boots", () -> new MagmiteArmorItem.Boots());
	public static final RegistryObject<Item> COOLANT_ARMOR_HELMET = REGISTRY.register("coolant_armor_helmet", () -> new CoolantArmorItem.Helmet());
	public static final RegistryObject<Item> COOLANT_ARMOR_CHESTPLATE = REGISTRY.register("coolant_armor_chestplate", () -> new CoolantArmorItem.Chestplate());
	public static final RegistryObject<Item> COOLANT_ARMOR_LEGGINGS = REGISTRY.register("coolant_armor_leggings", () -> new CoolantArmorItem.Leggings());
	public static final RegistryObject<Item> COOLANT_ARMOR_BOOTS = REGISTRY.register("coolant_armor_boots", () -> new CoolantArmorItem.Boots());
	public static final RegistryObject<Item> RHYOLITE_ARMOR_HELMET = REGISTRY.register("rhyolite_armor_helmet", () -> new RhyoliteArmorItem.Helmet());
	public static final RegistryObject<Item> RHYOLITE_ARMOR_CHESTPLATE = REGISTRY.register("rhyolite_armor_chestplate", () -> new RhyoliteArmorItem.Chestplate());
	public static final RegistryObject<Item> RHYOLITE_ARMOR_LEGGINGS = REGISTRY.register("rhyolite_armor_leggings", () -> new RhyoliteArmorItem.Leggings());
	public static final RegistryObject<Item> RHYOLITE_ARMOR_BOOTS = REGISTRY.register("rhyolite_armor_boots", () -> new RhyoliteArmorItem.Boots());
	public static final RegistryObject<Item> RUTILES_ARMOR_HELMET = REGISTRY.register("rutiles_armor_helmet", () -> new RutilesArmorItem.Helmet());
	public static final RegistryObject<Item> RUTILES_ARMOR_CHESTPLATE = REGISTRY.register("rutiles_armor_chestplate", () -> new RutilesArmorItem.Chestplate());
	public static final RegistryObject<Item> RUTILES_ARMOR_LEGGINGS = REGISTRY.register("rutiles_armor_leggings", () -> new RutilesArmorItem.Leggings());
	public static final RegistryObject<Item> RUTILES_ARMOR_BOOTS = REGISTRY.register("rutiles_armor_boots", () -> new RutilesArmorItem.Boots());
	public static final RegistryObject<Item> AQUAMARINE_ARMOR_HELMET = REGISTRY.register("aquamarine_armor_helmet", () -> new AquamarineArmorItem.Helmet());
	public static final RegistryObject<Item> AQUAMARINE_ARMOR_CHESTPLATE = REGISTRY.register("aquamarine_armor_chestplate", () -> new AquamarineArmorItem.Chestplate());
	public static final RegistryObject<Item> AQUAMARINE_ARMOR_LEGGINGS = REGISTRY.register("aquamarine_armor_leggings", () -> new AquamarineArmorItem.Leggings());
	public static final RegistryObject<Item> AQUAMARINE_ARMOR_BOOTS = REGISTRY.register("aquamarine_armor_boots", () -> new AquamarineArmorItem.Boots());
	public static final RegistryObject<Item> ALEXANDRITE_ORE = block(PookieModBlocks.ALEXANDRITE_ORE);
	public static final RegistryObject<Item> ALEXANDRITE_BLOCK = block(PookieModBlocks.ALEXANDRITE_BLOCK);
	public static final RegistryObject<Item> MAGMITE_ORE = block(PookieModBlocks.MAGMITE_ORE);
	public static final RegistryObject<Item> MAGMITE_BLOCK = block(PookieModBlocks.MAGMITE_BLOCK);
	public static final RegistryObject<Item> COOLANT_ORE = block(PookieModBlocks.COOLANT_ORE);
	public static final RegistryObject<Item> COOLANT_BLOCK = block(PookieModBlocks.COOLANT_BLOCK);
	public static final RegistryObject<Item> RHYOLITE_ORE = block(PookieModBlocks.RHYOLITE_ORE);
	public static final RegistryObject<Item> RHYOLITE_BLOCK = block(PookieModBlocks.RHYOLITE_BLOCK);
	public static final RegistryObject<Item> RUTILES_ORE = block(PookieModBlocks.RUTILES_ORE);
	public static final RegistryObject<Item> RUTILES_BLOCK = block(PookieModBlocks.RUTILES_BLOCK);
	public static final RegistryObject<Item> AQUAMARINE_ORE = block(PookieModBlocks.AQUAMARINE_ORE);
	public static final RegistryObject<Item> AQUAMARINE_BLOCK = block(PookieModBlocks.AQUAMARINE_BLOCK);
	public static final RegistryObject<Item> ALEXANDRITE = REGISTRY.register("alexandrite", () -> new AlexandriteItem());
	public static final RegistryObject<Item> MAGMITE = REGISTRY.register("magmite", () -> new MagmiteItem());
	public static final RegistryObject<Item> COOLANT_INGOT = REGISTRY.register("coolant_ingot", () -> new CoolantIngotItem());
	public static final RegistryObject<Item> RHYOLITE_DUST = REGISTRY.register("rhyolite_dust", () -> new RhyoliteDustItem());
	public static final RegistryObject<Item> RUTILES = REGISTRY.register("rutiles", () -> new RutilesItem());
	public static final RegistryObject<Item> AQUAMARINE = REGISTRY.register("aquamarine", () -> new AquamarineItem());
	public static final RegistryObject<Item> ALEXANDRITE_PICKAXE = REGISTRY.register("alexandrite_pickaxe", () -> new AlexandritePickaxeItem());
	public static final RegistryObject<Item> ALEXANDRITE_AXE = REGISTRY.register("alexandrite_axe", () -> new AlexandriteAxeItem());
	public static final RegistryObject<Item> ALEXANDRITE_SWORD = REGISTRY.register("alexandrite_sword", () -> new AlexandriteSwordItem());
	public static final RegistryObject<Item> ALEXANDRITE_SHOVEL = REGISTRY.register("alexandrite_shovel", () -> new AlexandriteShovelItem());
	public static final RegistryObject<Item> ALEXANDRITE_HOE = REGISTRY.register("alexandrite_hoe", () -> new AlexandriteHoeItem());
	public static final RegistryObject<Item> MAGMITE_PICKAXE = REGISTRY.register("magmite_pickaxe", () -> new MagmitePickaxeItem());
	public static final RegistryObject<Item> MAGMITE_AXE = REGISTRY.register("magmite_axe", () -> new MagmiteAxeItem());
	public static final RegistryObject<Item> MAGMITE_SWORD = REGISTRY.register("magmite_sword", () -> new MagmiteSwordItem());
	public static final RegistryObject<Item> MAGMITE_SHOVEL = REGISTRY.register("magmite_shovel", () -> new MagmiteShovelItem());
	public static final RegistryObject<Item> MAGMITE_HOE = REGISTRY.register("magmite_hoe", () -> new MagmiteHoeItem());
	public static final RegistryObject<Item> COOLANT_PICKAXE = REGISTRY.register("coolant_pickaxe", () -> new CoolantPickaxeItem());
	public static final RegistryObject<Item> COOLANT_AXE = REGISTRY.register("coolant_axe", () -> new CoolantAxeItem());
	public static final RegistryObject<Item> COOLANT_SWORD = REGISTRY.register("coolant_sword", () -> new CoolantSwordItem());
	public static final RegistryObject<Item> COOLANT_SHOVEL = REGISTRY.register("coolant_shovel", () -> new CoolantShovelItem());
	public static final RegistryObject<Item> COOLANT_HOE = REGISTRY.register("coolant_hoe", () -> new CoolantHoeItem());
	public static final RegistryObject<Item> RHYOLITE_PICKAXE = REGISTRY.register("rhyolite_pickaxe", () -> new RhyolitePickaxeItem());
	public static final RegistryObject<Item> RHYOLITE_AXE = REGISTRY.register("rhyolite_axe", () -> new RhyoliteAxeItem());
	public static final RegistryObject<Item> RHYOLITE_SWORD = REGISTRY.register("rhyolite_sword", () -> new RhyoliteSwordItem());
	public static final RegistryObject<Item> RHYOLITE_SHOVEL = REGISTRY.register("rhyolite_shovel", () -> new RhyoliteShovelItem());
	public static final RegistryObject<Item> RHYOLITE_HOE = REGISTRY.register("rhyolite_hoe", () -> new RhyoliteHoeItem());
	public static final RegistryObject<Item> RUTILES_PICKAXE = REGISTRY.register("rutiles_pickaxe", () -> new RutilesPickaxeItem());
	public static final RegistryObject<Item> RUTILES_AXE = REGISTRY.register("rutiles_axe", () -> new RutilesAxeItem());
	public static final RegistryObject<Item> RUTILES_SWORD = REGISTRY.register("rutiles_sword", () -> new RutilesSwordItem());
	public static final RegistryObject<Item> RUTILES_SHOVEL = REGISTRY.register("rutiles_shovel", () -> new RutilesShovelItem());
	public static final RegistryObject<Item> RUTILES_HOE = REGISTRY.register("rutiles_hoe", () -> new RutilesHoeItem());
	public static final RegistryObject<Item> AQUAMARINE_PICKAXE = REGISTRY.register("aquamarine_pickaxe", () -> new AquamarinePickaxeItem());
	public static final RegistryObject<Item> AQUAMARINE_AXE = REGISTRY.register("aquamarine_axe", () -> new AquamarineAxeItem());
	public static final RegistryObject<Item> AQUAMARINE_SWORD = REGISTRY.register("aquamarine_sword", () -> new AquamarineSwordItem());
	public static final RegistryObject<Item> AQUAMARINE_SHOVEL = REGISTRY.register("aquamarine_shovel", () -> new AquamarineShovelItem());
	public static final RegistryObject<Item> AQUAMARINE_HOE = REGISTRY.register("aquamarine_hoe", () -> new AquamarineHoeItem());
	public static final RegistryObject<Item> STEELPLATESTAIRS = block(PookieModBlocks.STEELPLATESTAIRS);
	public static final RegistryObject<Item> STEELVENTSTAIRS = block(PookieModBlocks.STEELVENTSTAIRS);
	public static final RegistryObject<Item> STEELVENTBLOCK = block(PookieModBlocks.STEELVENTBLOCK);
	public static final RegistryObject<Item> STEELSHEETBLOCK = block(PookieModBlocks.STEELSHEETBLOCK);
	public static final RegistryObject<Item> STEELSHEETSTAIRS = block(PookieModBlocks.STEELSHEETSTAIRS);
	public static final RegistryObject<Item> STEELBOARDBLOCK = block(PookieModBlocks.STEELBOARDBLOCK);
	public static final RegistryObject<Item> STEELBOARDSTAIRS = block(PookieModBlocks.STEELBOARDSTAIRS);
	public static final RegistryObject<Item> STEELBOARDSLAB = block(PookieModBlocks.STEELBOARDSLAB);
	public static final RegistryObject<Item> STEELPLATESLAB = block(PookieModBlocks.STEELPLATESLAB);
	public static final RegistryObject<Item> STEELSHEETSLAB = block(PookieModBlocks.STEELSHEETSLAB);
	public static final RegistryObject<Item> STEELVENTSLAB = block(PookieModBlocks.STEELVENTSLAB);
	public static final RegistryObject<Item> STEELTRUSSBLOCK = block(PookieModBlocks.STEELTRUSSBLOCK);
	public static final RegistryObject<Item> STEELROD = REGISTRY.register("steelrod", () -> new SteelrodItem());
	public static final RegistryObject<Item> DICKONASTICK = REGISTRY.register("dickonastick", () -> new DickonastickItem());
	public static final RegistryObject<Item> BLUEWEURM_SPAWN_EGG = REGISTRY.register("blueweurm_spawn_egg", () -> new ForgeSpawnEggItem(PookieModEntities.BLUEWEURM, -16776961, -1, new Item.Properties()));
	public static final RegistryObject<Item> GREENWEURM_SPAWN_EGG = REGISTRY.register("greenweurm_spawn_egg", () -> new ForgeSpawnEggItem(PookieModEntities.GREENWEURM, -13382656, -1, new Item.Properties()));
	public static final RegistryObject<Item> ALBINOWOM_SPAWN_EGG = REGISTRY.register("albinowom_spawn_egg", () -> new ForgeSpawnEggItem(PookieModEntities.ALBINOWOM, -1, -39322, new Item.Properties()));
	public static final RegistryObject<Item> PINKWOM_SPAWN_EGG = REGISTRY.register("pinkwom_spawn_egg", () -> new ForgeSpawnEggItem(PookieModEntities.PINKWOM, -65281, -1, new Item.Properties()));
	public static final RegistryObject<Item> ECHOREMNANT_SPAWN_EGG = REGISTRY.register("echoremnant_spawn_egg", () -> new ForgeSpawnEggItem(PookieModEntities.ECHOREMNANT, -16777216, -16764109, new Item.Properties()));
	public static final RegistryObject<Item> FRAGMENT_SPAWN_EGG = REGISTRY.register("fragment_spawn_egg", () -> new ForgeSpawnEggItem(PookieModEntities.FRAGMENT, -16777216, -65536, new Item.Properties()));
	public static final RegistryObject<Item> EXPLOSIVEDRILL = block(PookieModBlocks.EXPLOSIVEDRILL);
	public static final RegistryObject<Item> AUIJKGHNJU = block(PookieModBlocks.AUIJKGHNJU);
	public static final RegistryObject<Item> PRESSURIZER = block(PookieModBlocks.PRESSURIZER);
	public static final RegistryObject<Item> BLACKIRON_ARMOR_HELMET = REGISTRY.register("blackiron_armor_helmet", () -> new BlackironArmorItem.Helmet());
	public static final RegistryObject<Item> BLACKIRON_ARMOR_CHESTPLATE = REGISTRY.register("blackiron_armor_chestplate", () -> new BlackironArmorItem.Chestplate());
	public static final RegistryObject<Item> BLACKIRON_ARMOR_LEGGINGS = REGISTRY.register("blackiron_armor_leggings", () -> new BlackironArmorItem.Leggings());
	public static final RegistryObject<Item> BLACKIRON_ARMOR_BOOTS = REGISTRY.register("blackiron_armor_boots", () -> new BlackironArmorItem.Boots());
	public static final RegistryObject<Item> BLACKIRON_ORE = block(PookieModBlocks.BLACKIRON_ORE);
	public static final RegistryObject<Item> BLACKIRON_BLOCK = block(PookieModBlocks.BLACKIRON_BLOCK);
	public static final RegistryObject<Item> BLACKIRON = REGISTRY.register("blackiron", () -> new BlackironItem());
	public static final RegistryObject<Item> BLACKIRON_PICKAXE = REGISTRY.register("blackiron_pickaxe", () -> new BlackironPickaxeItem());
	public static final RegistryObject<Item> BLACKIRON_AXE = REGISTRY.register("blackiron_axe", () -> new BlackironAxeItem());
	public static final RegistryObject<Item> BLACKIRON_SWORD = REGISTRY.register("blackiron_sword", () -> new BlackironSwordItem());
	public static final RegistryObject<Item> BLACKIRON_SHOVEL = REGISTRY.register("blackiron_shovel", () -> new BlackironShovelItem());
	public static final RegistryObject<Item> BLACKIRON_HOE = REGISTRY.register("blackiron_hoe", () -> new BlackironHoeItem());
	public static final RegistryObject<Item> BATTERY = REGISTRY.register("battery", () -> new BatteryItem());
	public static final RegistryObject<Item> DARLING = REGISTRY.register("darling", () -> new DarlingItem());
	public static final RegistryObject<Item> REVEX = REGISTRY.register("revex", () -> new RevexItem());
	public static final RegistryObject<Item> VICTIM = REGISTRY.register("victim", () -> new LunarItem());
	public static final RegistryObject<Item> QUARTZ_ARMOR_HELMET = REGISTRY.register("quartz_armor_helmet", () -> new QuartzArmorItem.Helmet());
	public static final RegistryObject<Item> QUARTZ_ARMOR_CHESTPLATE = REGISTRY.register("quartz_armor_chestplate", () -> new QuartzArmorItem.Chestplate());
	public static final RegistryObject<Item> QUARTZ_ARMOR_LEGGINGS = REGISTRY.register("quartz_armor_leggings", () -> new QuartzArmorItem.Leggings());
	public static final RegistryObject<Item> QUARTZ_ARMOR_BOOTS = REGISTRY.register("quartz_armor_boots", () -> new QuartzArmorItem.Boots());
	public static final RegistryObject<Item> QUARTZ_PICKAXE = REGISTRY.register("quartz_pickaxe", () -> new QuartzPickaxeItem());
	public static final RegistryObject<Item> QUARTZ_AXE = REGISTRY.register("quartz_axe", () -> new QuartzAxeItem());
	public static final RegistryObject<Item> QUARTZ_SWORD = REGISTRY.register("quartz_sword", () -> new QuartzSwordItem());
	public static final RegistryObject<Item> QUARTZ_SHOVEL = REGISTRY.register("quartz_shovel", () -> new QuartzShovelItem());
	public static final RegistryObject<Item> QUARTZ_HOE = REGISTRY.register("quartz_hoe", () -> new QuartzHoeItem());
	public static final RegistryObject<Item> DECIMATOR_SPAWN_EGG = REGISTRY.register("decimator_spawn_egg", () -> new ForgeSpawnEggItem(PookieModEntities.DECIMATOR, -1, -1, new Item.Properties()));

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
